should work

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,10 +28,14 @@ jobs:
         run: npm install
 
       - name: Bump version and generate change logs
+        id: release
         run: |
           git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
           git config --global user.name ${{ secrets.GIT_USER_NAME }}
-          npm run release -- --verbose || { echo "standard-version failed"; exit 1; }
+          npm run release || { echo "standard-version failed"; exit 1; }
+
+          NEW_TAG=$(git describe --tags --abbrev=0)
+          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT
           
       - name: Push changes
         run: |
@@ -48,5 +52,6 @@ jobs:
       - name: Create Github Release
         uses: softprops/action-gh-release@v2.2.2
         with:
+          tag_name: ${{ steps.release.outputs.tag }}
           body_path: CHANGELOG.md
           fail_on_unmatched_files: false
